---
# Enable line length check, set to 80 for readability
MD013:
    line_length: 120
    # Allow headings to exceed line length
    headings: false
    # Allow code blocks to exceed line length
    code_blocks: false

# Require ATX-style headings (# instead of = or -)
MD003:
    style: atx

# Enforce consistent list indentation
MD007:
    indent: 4

# Allow multiple consecutive blank lines for flexibility
MD012: false

# Enforce trailing punctuation in headings for consistency
MD026:
    punctuation: '.,;:!?'

# Allow inline HTML for flexibility in Markdown rendering
MD033: false

# Disable first-line heading requirement
# to allow flexibility in document structure
MD041: false

# Dollar signs used before commands without showing output
MD014: true

# Disable no-space-in-emphasis to allow flexibility in emphasis formatting
MD036: false

# Lists should be surrounded by blank lines
MD032: true

MD046:
    style: fenced
